admin1_homepage:
    path:     /aabbcc
    defaults: { _controller: AdminBundle:Default:index }

admin1_testpage:
    path:     /abc
    defaults: { _controller: AdminBundle:Default:getTypeNumber }

admin_api_blog_get:
    path:     /blog/{typeId}/{page}/{limit}
    defaults: { _controller: AdminBundle:Default:getBlog }
    methods: [GET]

admin_api_type_get:
     path:     /type
     defaults: { _controller: AdminBundle:Default:getType }
     methods: [GET]

admin_test_page:
      path:     /preEdit/{id}
      defaults: { _controller: AdminBundle:Default:preEdit }
      requirements:
        id: \d+