admin1_homepage:
    path:     /aabbcc
    defaults: { _controller: AdminBundle:Default:getType }

admin1_testpage:
    path:     /abc
    defaults: { _controller: AdminBundle:Default:getTypeNumber }

admin_api_blog_get:
    path:     /blog/{typeId}/{page}/{limit}
    defaults: { _controller: AdminBundle:Default:getBlog }