admin1_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin1_postpage:
    path:     /post
    defaults: { _controller: AdminBundle:Default:post }

admin1_testpage:
    path:     /abc
    defaults: { _controller: AdminBundle:Default:getTypeNumber }

admin_api_blog_get:
    path:     /blog/{typeId}/{page}/{limit}
    defaults: { _controller: AdminBundle:Default:getBlog }
    methods: [GET]

admin_api_type_get:
     path:     /type
     defaults: { _controller: AdminBundle:Default:getType }
     methods: [GET]

admin_test_page:
      path:     /preEdit/{id}
      defaults: { _controller: AdminBundle:Default:preEdit }
      requirements:
          id: \d+

admin_delete_blog:
      path:     /delete/{blogId}
      defaults: { _controller: AdminBundle:Default:deleteBlog }
      methods: [GET]
      requirements:
          id: \d+

admin_post_new_version:
      path:     /version
      defaults: { _controller: AdminBundle:Default:postNewVersion }
      methods: [POST]


admin_change_blog_version:
      path:     /changeBlogVersion
      defaults: { _controller: AdminBundle:Default:changeBlogVersion }
      methods: [POST]