<?php

namespace BlogBundle\Repository;

/**
 * PrivatePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivatePostRepository extends \Doctrine\ORM\EntityRepository
{
}
