services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    blog.manager:
        class: BlogBundle\Service\BlogService
        arguments: ["@service_container", "@request_stack"]

    version.manager:
        class: BlogBundle\Service\VersionService
        arguments: ["@service_container", "@request_stack"]

    type.manager:
        class: BlogBundle\Service\TypeService
        arguments: ["@service_container"]

    cache.manager:
        class: BlogBundle\Service\CacheService