services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    blog.manager:
        class: BlogBundle\Service\BlogService
        arguments: ["@service_container"]