app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

admin_editpage:
    path:     /admin/post
    defaults: { _controller: AppBundle:Admin:post }


app_api_type:
    path:   /api/v1/type
    defaults: { _controller: AppBundle:Api:type }
    methods: [get]

app_api_blog:
    path:   /api/v1/blog
    defaults: { _controller: AppBundle:Api:blog }
    methods: [post,get]

admin_testpage:
    path:   /test
    defaults: { _controller: AppBundle:Admin:test }