app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


app_api_type:
    path:   /api/v1/type
    defaults: { _controller: AppBundle:Api:type }
    methods: [get]

app_api_blog:
    path:   /api/v1/blog
    defaults: { _controller: AppBundle:Api:blog }
    methods: [post,get]
