app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

admin_editpage:
    path:     /admin/post
    defaults: { _controller: AppBundle:Admin:post }